service: sanket-hello-world-app
provider:
  name: aws
  runtime: nodejs16.x
  stage: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events:
      - http:
        path: /
        method: ANY
        cors: true
      - http:
        path: /{proxy+}
        method: ANY
        cors: true
