service: aws-node-express-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  stage: dev
  environment:
    SEQUELIZE_DB_HOST: localhost
    SEQUELIZE_DB_USERNAME: postgres
    SEQUELIZE_DB_PASSWORD: postgres
    SEQUELIZE_DB_DATABASE: boilerplate
    MESSAGE: ${self:custom.appEnv.MESSAGE.${self:custom.appStage}}

custom:
  appStage: ${opt:stage, self:provider.stage}
  appEnv:
    MESSAGE:
      prod: "This is production environment"
      dev: "This is development environment"
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.prod
  include:
    - config/.env.dev

functions:
  
  getUsers:
    handler: app/handler/user-handler.getUsersHandler
    events:
      - httpApi:
          method: POST
          path: /rewrite/getUsers/{page}
  getUserById:
    handler: app/handler/user-handler.getUserByIdHandler
    events:
      - httpApi:
          method: POST
          path: /rewrite/getUserById/{id}
          
  createUser:
    handler: app/handler/user-handler.createUserHandler
    events:
      - httpApi:
          method: POST
          path: /rewrite/createUser
  updateUser:
    handler: app/handler/user-handler.updateUserHandler
    events:
      - httpApi:
          method: PUT
          path: /rewrite/updateUser/{id}
  deleteUser:
    handler: app/handler/user-handler.deleteUserHandler
    events:
      - httpApi:
          method: DELETE
          path: /rewrite/deleteUser/{id}
          
      
