service: aws-node-express-typescript

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.prod
  include:
    - config/.env.dev

functions:
  api:
    handler: app/index.serverApp
    events:
      - httpApi: "*"
      
